apiVersion: v1
kind: Service
metadata:
  name: {{ include "chaqna-xeon-backend-server.fullname" . }}-svc
  labels:
  {{- include "chaqna-xeon-backend-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.svc.type }}
  selector:
    app: chaqna-xeon-backend-server-deploy
  {{- include "chaqna-xeon-backend-server.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.svc.ports | toYaml | nindent 2 -}}