apiVersion: v1
kind: Service
metadata:
  name: {{ include "tgi-service.fullname" . }}-vc
  labels:
  {{- include "tgi-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.svc.type }}
  selector:
    app: tgi-service-deploy
  {{- include "tgi-service.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.svc.ports | toYaml | nindent 2 -}}