apiVersion: v1
kind: Service
metadata:
  name: {{ include "llm.fullname" . }}-svc
  labels:
  {{- include "llm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.svc.type }}
  selector:
    app: llm-deploy
  {{- include "llm.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.svc.ports | toYaml | nindent 2 }}