apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/name: vllm-gaudi-exporter
    app.kubernetes.io/version: v0.0.1
    release: prometheus-stack
  name: vllm-gaudi-exporter
  namespace: monitoring
spec:
  namespaceSelector:
      any: true
  selector:
    matchLabels:
      app.kubernetes.io/name: vllm
  endpoints:
  - port: vllm
    interval: 5s
