{
 "title": "LLM-Deployment-Solution",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Request Total Duration(s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "request_total_dur_s", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Avg Latency Per Token(ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "request_avg_token_latency_ms", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Request Frist Token Latency(ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "request_first_token_latency_ms", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Request Next Token Latency(ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "request_next_token_latency_ms", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Request Prompt Tokens Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "request_prompt_tokens", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Request Completion Tokens Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expr": "request_completion_tokens", "legendFormat": "__auto" }
   ]
  }
 ]
}