# AMD CPUs
#  Naples
- architecture: Zen
  family: 23
  models:
  - 1
  minstepping: "0"
  maxstepping: "0"
  channels: 8
#  Rome
- architecture: Zen2
  family: 23
  models:
  - 49
  minstepping: "0"
  maxstepping: "0"
  channels: 8
#  Milan
- architecture: Zen3
  family: 25
  models:
  - 1
  minstepping: "0"
  maxstepping: "0"
  channels: 8

# ARM CPUs
#  AWS Graviton 2
- architecture: Neoverse N1
  family: 0
  models:
  - 1
  minstepping: r3p1
  maxstepping: r3p1
  channels: 8
#  AWS Graviton 3
- architecture: Neoverse V1
  family: 0
  models:
  - 1
  minstepping: r1p1
  maxstepping: r1p1
  channels: 8
