# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

# Default values for llm-uservice.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1


image:
  repository: opea/gen-ai-comps:embedding-tei-server
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  # tag: "1.0"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  # The default port for llm service is 9000
  port: 6000
  targetPort: 6000 

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

# To override values in subchart tei
tei:
  hftei:
    modelId: m-a-p/OpenCodeInterpreter-DS-6.7B
    # modelId: /data/OpenCodeInterpreter-DS-6.7B
    port: 80
    volume: /mnt/model

  image:
    repository: ghcr.io/huggingface/text-generation-inference
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "1.4"

global:
  qnaConfig:
    REDIS_URL: "redis://chaqna-xeon-redis-vector-db.default.svc.cluster.local:6379"
    INDEX_NAME: "rag-redis"
    EMBEDDING_MODEL_ID: "BAAI/bge-base-en-v1.5"
    RERANK_MODEL_ID: "BAAI/bge-reranker-large"
    LLM_MODEL_ID: "Intel/neural-chat-7b-v3-3"
    TEI_EMBEDDING_ENDPOINT: "http://chaqna-xeon-tei-embedding-service-svc.default.svc.cluster.local:6006"
    TEI_RERANKING_ENDPOINT: "http://chaqna-xeon-tei-xeon-service-svc.default.svc.cluster.local:8808"
    TGI_LLM_ENDPOINT: "http://chaqna-xeon-tgi-service-svc.default.svc.cluster.local:9009"
    MEGA_SERVICE_HOST_IP: "172.16.3.15"
    HUGGINGFACEHUB_API_TOKEN: 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
    CHAT_BASE_URL: "${chat_qna_backendurl}/v1/chatqna"