apiVersion: v1
kind: Service
metadata:
  name: {{ include "retriever.fullname" . }}-svc
  labels:
  {{- include "retriever.labels" . | nindent 4 }}
spec:
  type: {{ .Values.svc.type }}
  selector:
    app: retriever-deploy
  {{- include "retriever.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.svc.ports | toYaml | nindent 2 }}