apiVersion: v1
kind: Service
metadata:
  name: cadvisor-service
  namespace: monitoring
  labels:
    app: cadvisor-service
spec:
  ports:
  - name: cadvisor-metrics
    port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: Endpoints
metadata:
  name: cadvisor-service
  namespace: monitoring
  labels:
    app: cadvisor-service
subsets:
- addresses:
  - ip: 100.83.122.244
  ports:
  - name: cadvisor-metrics
    port: 8080
