apiVersion: v1
kind: Service
metadata:
  name: {{ include "tei-embedding-service.fullname" . }}-svc
  labels:
  {{- include "tei-embedding-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.svc.type }}
  selector:
    app: tei-embedding-service-deploy
  {{- include "tei-embedding-service.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.svc.ports | toYaml | nindent 2 -}}