serviceDeploy:
  replicas: 1
  teiRerankingServiceDeploy:
    args:
    - --model-id
    - $(RERANK_MODEL_ID)
    image:
      repository: ghcr.io/huggingface/text-embeddings-inference
      tag: cpu-1.2
kubernetesClusterDomain: cluster.local
svc:
  ports:
  - name: service
    nodePort: 30808
    port: 8808
    targetPort: 80
  type: NodePort
