# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: {{ include "embedding-uservice.fullname" . }}
  labels:
    {{- include "embedding-uservice.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: embedding-uservice
  selector:
    {{- include "embedding-uservice.selectorLabels" . | nindent 4 }}
