apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/name: tei-reranking-exporter
    app.kubernetes.io/version: v0.0.1
    release: prometheus-stack
  name: tei-reranking-exporter
  namespace: monitoring
spec:
  namespaceSelector:
      any: true
  selector:
    matchLabels:
      app: tei-reranking-service-deploy
  endpoints:
  - port: tei-reranking-svc
    interval: 5s
