# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tgi-gaudi-service-deploy
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tgi-gaudi-service-deploy
  template:
    metadata:
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
      labels:
        app: tgi-gaudi-service-deploy
    spec:
      hostIPC: true
      containers:
      - envFrom:
        - configMapRef:
            name: qna-config
        image: ghcr.io/huggingface/tgi-gaudi:1.2.1
        name: tgi-gaudi-service-deploy-demo
        args:
        - --model-id
        - $(LLM_MODEL_ID)
        #- "/data/Llama-2-7b-hf"
        # - "/data/Mistral-7B-Instruct-v0.2"
        # - --quantize
        # - "bitsandbytes-fp4"
#        - --disable-custom-kernels
        volumeMounts:
        - mountPath: /data
          name: model-volume
        - mountPath: /dev/shm
          name: shm
        ports:
        - containerPort: 80
        resources:
          limits:
            habana.ai/gaudi: 1
          # limits:
          #   cpu: 56000m
          #   memory: 26Gi
          # requests:
          #   cpu: 56000m
          #   memory: 26Gi
      serviceAccountName: default
      nodeSelector:
      volumes:
      - name: model-volume
        hostPath:
          # directory location on host
          path: /mnt/data0/weights
          # this field is optional
          type: Directory
      - name: shm
        emptyDir:
          medium: Memory
          sizeLimit: 1Gi
---
kind: Service
apiVersion: v1
metadata:
  name: tgi-gaudi-svc
spec:
  type: NodePort
  selector:
    app: tgi-gaudi-service-deploy
  ports:
    - name: service
      port: 9009
      targetPort: 80
