# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ConfigMap
metadata:
  name: qna-config
  namespace: default
data:
  EMBEDDING_MODEL_ID: "BAAI/bge-base-en-v1.5"
  RERANK_MODEL_ID: "BAAI/bge-reranker-base"
    #LLM_MODEL_ID: "Intel/neural-chat-7b-v3-3"
  LLM_MODEL_ID: "mistralai/Mixtral-8x7B-v0.1"
    #LLM_MODEL_ID: "/data/Mixtral-8x7B-v0.1"
  TEI_EMBEDDING_ENDPOINT: "http://tei-embedding-svc.default.svc.cluster.local:6006"
  TEI_RERANKING_ENDPOINT: "http://tei-reranking-svc.default.svc.cluster.local:8808"
  TGI_LLM_ENDPOINT: "http://tgi-gaudi-svc.default.svc.cluster.local:9009"
  REDIS_URL: "redis://redis-vector-db.default.svc.cluster.local:6379"
  INDEX_NAME: "rag-redis"
  HUGGING_FACE_HUB_TOKEN: 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
  HUGGINGFACEHUB_API_TOKEN: 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
  EMBEDDING_SERVICE_HOST_IP: embedding-svc
  RETRIEVER_SERVICE_HOST_IP: retriever-svc
  RERANK_SERVICE_HOST_IP: reranking-svc
  LLM_SERVICE_HOST_IP: llm-svc
    #PT_HPU_ENABLE_LAZY_COLLECTIVES: "true"
    #OMPI_MCA_btl_vader_single_copy_mechanism: "none"
