# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tgi-gaudi-service-deploy
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tgi-gaudi-service-deploy
  template:
    metadata:
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
      labels:
        app: tgi-gaudi-service-deploy
    spec:
      hostIPC: true
      containers:
      - envFrom:
        - configMapRef:
            name: qna-config
        env:
        - name: OMPI_MCA_btl_vader_single_copy_mechanism
          value: "none"
        - name: PT_HPU_ENABLE_LAZY_COLLECTIVES
          value: "true"
        - name: runtime
          value: "habana"
        - name: HABANA_VISIBLE_DEVICES
          value: "all"
        - name: QUANT_CONFIG
          value: "/data/maxabs_quant.json"
        image: ghcr.io/huggingface/tgi-gaudi:2.0.0
        name: tgi-gaudi-service-deploy-demo
        securityContext:
          capabilities:
            add: ["SYS_NICE"]
        args:
        - --model-id
        - $(LLM_MODEL_ID)
        - --sharded 
        - "true" 
        - --num-shard 
        - "4"
        - --max-input-length 
        - "1024"
        - --max-total-tokens 
        - "2048"
        volumeMounts:
        - mountPath: /data
          name: model-volume
        - mountPath: /dev/shm
          name: shm
        ports:
        - containerPort: 80
        resources:
          limits:
            habana.ai/gaudi: 4
      serviceAccountName: default
      nodeSelector:
      volumes:
      - name: model-volume
        hostPath:
          # directory location on host
          path: /mnt/models
          # this field is optional
          type: Directory
      - name: shm
        emptyDir:
          medium: Memory
          sizeLimit: 1Gi
---
kind: Service
apiVersion: v1
metadata:
  name: tgi-gaudi-svc
spec:
  type: ClusterIP
  selector:
    app: tgi-gaudi-service-deploy
  ports:
    - name: service
      port: 9009
      targetPort: 80
