# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ConfigMap
metadata:
  name: qna-config
data:
  http_proxy: "http://192.168.1.253:3128"
  https_proxy: "http://192.168.1.253:3128"
  no_proxy: ".${K8S_NS}.svc.cluster.local,.intel.com,10.0.0.0/8,192.168.0.0/16,localhost,127.0.0.0/8,134.134.0.0/16,10.238.154.145,192.168.1.3"

  EMBEDDING_MODEL_ID: "BAAI/bge-base-en-v1.5"
  RERANK_MODEL_ID: "BAAI/bge-reranker-large"
  LLM_MODEL_ID: "/data/neural-chat-7b-v3-3"
  TEI_EMBEDDING_ENDPOINT: "http://tei-embedding-svc.${K8S_NS}.svc.cluster.local:6006"
  TEI_RERANKING_ENDPOINT: "http://tei-reranking-svc.${K8S_NS}.svc.cluster.local:8808"
  TGI_LLM_ENDPOINT: "http://tgi-svc.${K8S_NS}.svc.cluster.local:9009"
  REDIS_URL: "redis://redis-vector-db.${K8S_NS}.svc.cluster.local:6379"
  INDEX_NAME: "rag-redis"
  HUGGINGFACEHUB_API_TOKEN: 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
  EMBEDDING_SERVICE_HOST_IP: embedding-svc
  RETRIEVER_SERVICE_HOST_IP: retriever-svc
  RERANK_SERVICE_HOST_IP: reranking-svc
  LLM_SERVICE_HOST_IP: llm-svc
