apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chaqna-xeon-ui-server.fullname" . }}-deploy
  labels:
  {{- include "chaqna-xeon-ui-server.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.deploy.replicas }}
  selector:
    matchLabels:
      app: chaqna-xeon-ui-server-deploy
    {{- include "chaqna-xeon-ui-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: chaqna-xeon-ui-server-deploy
      {{- include "chaqna-xeon-ui-server.selectorLabels" . | nindent 8 }}
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
    spec:
      containers:
      - env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        - name: CHAT_BASE_URL
          value: {{ .Values.global.qnaConfig.CHAT_BASE_URL | quote }}
        image: {{ .Values.deploy.chaqnaXeonUiServerDeploy.image.repository }}:{{ .Values.deploy.chaqnaXeonUiServerDeploy.image.tag
          | default .Chart.AppVersion }}
        name: chaqna-xeon-ui-server-deploy
        ports:
        - containerPort: 5173
        resources: {}
      hostIPC: true
      serviceAccountName: default