apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2023-03-22T05:27:08Z"
  generation: 1
  name: ei-infer-deployment-pose-sample-q03
  namespace: default
  resourceVersion: "6968431"
  uid: cb8eaf39-7cb2-4a09-89ca-f648fb0d9f25
spec:
  progressDeadlineSeconds: 86400
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ei-infer-pose-multi-queue-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ei-infer-pose-multi-queue-app
    spec:
      containers:
      - env:
        - name: INFER_MODEL_NAME
          value: ssd_mobilenet_bf16
        - name: INPUT_QUEUE_HOST
          value: ei-redis-svc
        - name: OUTPUT_BROKER_HOST
          value: ei-redis-svc
        - name: INFER_TYPE
          value: pose-sample-q03
        - name: ONEDNN_MAX_CPU_ISA
          value: AVX512_CORE_AMX
        - name: OMP_NUM_THREADS
          value: "1"
        - name: TF_NUM_INTEROP_THREADS
          value: "1"
        - name: TF_NUM_INTRAOP_THREADS
          value: "4"
        image: gar-registry.caas.intel.com/cpio/ei-inference-service-tensorflow:2023WW11
        imagePullPolicy: IfNotPresent
        name: ei-infer-pose-multi-queue-app
        ports:
        - containerPort: 8000
          name: web
          protocol: TCP
        resources:
          limits:
            cpu: "2"
            memory: 4Gi
          requests:
            cpu: "2"
            memory: 4Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      initContainers:
      - command:
        - sh
        - -c
        - until nslookup ei-redis-svc; do echo waiting for ei-redis-svc; sleep 2;
          done;
        image: busybox:1.31
        imagePullPolicy: IfNotPresent
        name: init-ei-infer-pose-multi-queue-app
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      nodeSelector:
        css-actor: demo
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-03-22T05:28:25Z"
    lastUpdateTime: "2023-03-22T05:28:25Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2023-03-22T05:27:08Z"
    lastUpdateTime: "2023-03-22T05:28:25Z"
    message: ReplicaSet "ei-infer-deployment-pose-sample-q03-d5b6b995f" has successfully
      progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
