apiVersion: v1
kind: Service
metadata:
  name: {{ include "reranking.fullname" . }}-svc
  labels:
  {{- include "reranking.labels" . | nindent 4 }}
spec:
  type: {{ .Values.svc.type }}
  selector:
    app: reranking-deploy
  {{- include "reranking.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.svc.ports | toYaml | nindent 2 }}