FROM chzhyang/chatglm2-6b-api:v1

# Install any necessary dependencies or packages
#RUN apt-get update && apt-get install -y <your-package>

# Add your custom scripts or files to the container
#COPY . .

# Set the working directory
#WORKDIR /BigDL

# Run a command to keep the container running
CMD python service-api.py
