kubernetesClusterDomain: cluster.local
llmDeploy:
  llmDeployDemo:
    env:
      framework: openvino
      llamaCppThreads: "16"
      metricPort: "8090"
      modelDtype: int8
      modelName: llama2-7b
      modelPath: /models/llama2-7b-ov-int8
      ompNumThreads: "16"
      svcPort: "8000"
    image:
      repository: ccr-registry.caas.intel.com/cnbench/llm-server 
      tag: v2-slim-latest 
    resources:
      limits:
        cpu: "16"
        memory: 28Gi
      requests:
        cpu: "16"
        memory: 28Gi
  nodeSelector:
    llmdemo: "true"
  ports:
  - name: service
    nodePort: 30021
    port: 8080
    targetPort: 8000
  - name: metric-service
    nodePort: 30022
    port: 8090
    targetPort: 8090
  replicas: 1
  type: NodePort
