apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-deploy
  labels:
  {{- include "llm-deploy-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.llmDeploy.replicas }}
  selector:
    matchLabels:
      app: llm-deploy
    {{- include "llm-deploy-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: llm-deploy
      {{- include "llm-deploy-chart.selectorLabels" . | nindent 8 }}
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
    spec:
      containers:
      - command:
        - conda
        - run
        - --no-capture-output
        - -n
        - llmenv
        - python
        - api.py
        env:
        - name: OMP_NUM_THREADS
          value: {{ quote .Values.llmDeploy.llmDeployDemo.env.ompNumThreads }}
        - name: LLM_SERVER_N_THREADS
          value: {{ quote .Values.llmDeploy.llmDeployDemo.env.llamaCppThreads }}
        - name: LLM_SERVER_MODEL_NAME
          value: {{ quote .Values.llmDeploy.llmDeployDemo.env.modelName }}
        - name: LLM_SERVER_MODEL_PATH
          value: {{ quote .Values.llmDeploy.llmDeployDemo.env.modelPath }}
        - name: LLM_SERVER_MODEL_DTYPE
          value: {{ quote .Values.llmDeploy.llmDeployDemo.env.modelDtype }}
        - name: LLM_SERVER_BACKEND
          value: {{ quote .Values.llmDeploy.llmDeployDemo.env.framework }}
        - name: LLM_SERVER_SVC_PORT
          value: {{ quote .Values.llmDeploy.llmDeployDemo.env.svcPort }}
        - name: LLM_SERVER_METRIC_PORT
          value: {{ quote .Values.llmDeploy.llmDeployDemo.env.metricPort }}
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.llmDeploy.llmDeployDemo.image.repository }}:{{ .Values.llmDeploy.llmDeployDemo.image.tag
          | default .Chart.AppVersion }}
        name: llm-deploy-demo
        ports:
        - containerPort: 8000
        - containerPort: 8090
        resources: {{- toYaml .Values.llmDeploy.llmDeployDemo.resources | nindent 10 }}
        volumeMounts:
        - mountPath: /models
          name: model-volume
        - mountPath: /opt/miniconda3
          name: libs-volume          
      nodeSelector: {{- toYaml .Values.llmDeploy.nodeSelector | nindent 8 }}
      serviceAccountName: default
      volumes:
      - hostPath:
          path: /mnt/model
          type: Directory
        name: model-volume
      - hostPath:
          path: /mnt/miniconda3-docker
          type: Directory
        name: libs-volume        