apiVersion: v1
kind: ConfigMap
metadata:
  name: qna-config
  namespace: default
data:
  http_proxy: "http://proxy-dmz.intel.com:911"
  https_proxy: "http://proxy-dmz.intel.com:912"
  EMBEDDING_MODEL_ID: "BAAI/bge-base-en-v1.5"
  TEI_EMBEDDING_ENDPOINT: "http://${host_ip}:6006"
  REDIS_URL: "redis://${host_ip}:6379"
  INDEX_NAME: "rag-redis"
  TEI_EMBEDDING_ENDPOINT: "http://${host_ip}:6006"
  RERANK_MODEL_ID: "BAAI/bge-reranker-large"
  TEI_RERANKING_ENDPOINT: 
  HUGGINGFACEHUB_API_TOKEN: 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
  # ${HUGGINGFACEHUB_API_TOKEN}
  LLM_MODEL_ID: "Intel/neural-chat-7b-v3-3"
  TGI_LLM_ENDPOINT: "http://${your_ip}:9009"