apiVersion: apps/v1
kind: Deployment
metadata:
  name: milvus-insight
  labels:
    app: milvus-insight
spec:
  replicas: 1
  selector:
    matchLabels:
      app: milvus-insight
  template:
    metadata:
      labels:
        app: milvus-insight
    spec:
      containers:
        - name: milvus-insight
          image: milvusdb/milvus-insight:latest
          env:
            - name: MILVUS_URL
              value: "chatdemo-milvus:19530"
            - name: HOST_URL
              # value: "http://milvus-insight-service:3000"
              value: "http://otcloud-server.bj.intel.com:8100"
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: milvus-insight-service
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30800
  selector:
    app: milvus-insight