{
 "title": "MemBW Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rdt_container_cpu_utilization{nameSpace=\"benchmarking\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mem Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rdt_container_memory{nameSpace=\"benchmarking\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mem Bandwidth_all",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rdt_container_sum_total_memory_bandwidth{nameSpace=\"benchmarking\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mem Bandwidth_local",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rdt_container_sum_local_memory_bandwidth{nameSpace=\"benchmarking\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}