apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/name: membw-metric-exporter
    app.kubernetes.io/version: v0.0.1
    release: prometheus-stack
  name: membw-metric-exporter
  namespace: monitoring
spec:
  namespaceSelector:
      any: true
  selector:
    matchLabels:
      app: membw-service
  endpoints:
  - port: membw-metrics
    interval: 2s
