# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: memory-bandwidth-exporter
  namespace: system
spec:
  selector:
    matchLabels:
      app: memory-bandwidth-exporter
  template:
    metadata:
      labels:
        app: memory-bandwidth-exporter
    spec:
      nodeName: "satg-opea-4"
      containers:
      - name: memory-bandwidth-exporter
        image: docker201904/memory-bandwidth-exporter:v1.0
        imagePullPolicy: IfNotPresent
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: NAMESPACE_WHITELIST
          value: "calico-apiserver,calico-system,kube-system,tigera-operator"
        - name: COLLECTER_INTERVAL
          value: 1s
        - name: CONTAINER_METRICS
          value: "all"
        - name: CLASS_METRICS
          value: "none"
        - name: NODE_METRICS
          value: "none"
        - name: WEB_LISTEN_ADDRESS
          value: ":9100"
        volumeMounts:
        - name: hooks
          mountPath: /etc/containers/oci/hooks.d/
          readOnly: true
        - name: usr
          mountPath: /usr/
          readOnly: true
        - name: resctrl
          mountPath: /sys/fs/resctrl/
        - name: nri
          mountPath: /var/run/nri/
          readOnly: true
        securityContext:
          privileged: true
        ports:
        - containerPort: 9100
          name: http
      volumes:
      - name: hooks
        hostPath:
          path: /etc/containers/oci/hooks.d/
      - name: usr
        hostPath:
          path: /usr/
      - name: resctrl
        hostPath:
          path: /sys/fs/resctrl/
      - name: nri
        hostPath:
          path: /var/run/nri/
      hostPID: true
---
apiVersion: v1
kind: Service
metadata:
  name: membw-service
  namespace: system
  labels:
    app: membw-service
spec:
  selector:
    app: memory-bandwidth-exporter
  ports:
  - name: membw-metrics
    port: 9100
    targetPort: 9100
