apiVersion: v1
kind: Service
metadata:
  name: pcm-service
  namespace: monitoring
  labels:
    app: pcm-service
spec:
  ports:
  - name: pcm-metrics
    port: 9738
    targetPort: 9738
---
apiVersion: v1
kind: Endpoints
metadata:
  name: pcm-service
  namespace: monitoring
  labels:
    app: pcm-service
subsets:
- addresses:
  - ip: 192.168.1.3
  ports:
  - name: pcm-metrics
    port: 9738
