---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llm-deploy
  template:
    metadata:
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
      labels:
        app: llm-deploy
    spec:
      nodeSelector:
        llmdemo: "true"
      containers:
      - command:
        - /usr/bin/numactl
        - -C
        - 0-55,56-111
        - python3
        - llm_inference_api.py
        env:
        - name: OMP_NUM_THREADS
          value: "112"
        - name: MODEL_NAME
          value: "chatglm2-6b"
        - name: MODEL_PATH
          value: "/models/chatglm2-6b"
        - name: MODEL_DTYPE
          value: "fp16"
        - name: SVC_PORT
          value: "8000"
        - name: METRIC_PORT
          value: "8090"
        image: ccr-registry.caas.intel.com/cnbench/llm-inference-api:chatglm2.v1-metrics-port
        name: llm-deploy-demo
        volumeMounts:
        - mountPath: /models
          name: model-volume
        ports:
        - containerPort: 8000
        - containerPort: 8090
        resources:
          limits:
            cpu: 112000m
            memory: 26Gi
          requests:
            cpu: 112000m
            memory: 26Gi
      serviceAccountName: default
      volumes:
      - name: model-volume
        hostPath:
          # directory location on host
          path: /mnt/model
          # this field is optional
          type: Directory
---
kind: Service
apiVersion: v1
metadata:
  name: llm-deploy
  labels:
    app: llm-deploy
spec:
  type: NodePort
  selector:
    app: llm-deploy
  ports:
    - name: service
      port: 8080
      targetPort: 8000
      nodePort: 30021
    - name: metric-service
      port: 8090
      targetPort: 8090
      nodePort: 30022
