apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: llm-deploy
  labels:
    svc-monitor: llm-deploy
spec:
  selector:
    matchLabels:
      app: llm-deploy
  endpoints:
  - port: metric-service
    interval: 15s
