kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: ctlplane-daemonset
spec:
  selector:
    matchLabels:
      app: ctlplane-daemonset
  template:
    metadata:
      labels:
        app: ctlplane-daemonset
    spec:
      initContainers:
        - name: delete-old-state
          image: busybox:1.28
          command: ['rm', '-f', '/daemonstate/daemon.state']
          volumeMounts:
          - name: state
            mountPath: /daemonstate
      containers:
        - name: ctlplane-daemonset
          image: 10.250.18.9:5000/ctlplane:0.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 31000
          securityContext:
            privileged: true
          args: ["-cpath", "/cgroup", "-spath", "/daemonstate/daemon.state", "-runtime", "containerd", "-allocator", "numa-namespace=2"]
          volumeMounts:
          - name: host
            mountPath: /cgroup
          - name: state
            mountPath: /daemonstate
          readinessProbe:
            tcpSocket:
              port: 31000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 31000
            initialDelaySeconds: 15
            periodSeconds: 20
        - name: ctlplane-agent
          image: 10.250.18.9:5000/ctlplane:0.2
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          args: ["-a", "-namespace-prefix", "hotel-res"]
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
        - name: ctlplane-daemon-monitor
          image: 10.250.18.9:5000/ctlplane:0.2
          args: ["-spath", "/daemonstate/daemon.state", "-m"]
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8088
              name: monitor
          securityContext:
            privileged: true
          volumeMounts:
          - name: host
            mountPath: /cgroup
          - name: state
            mountPath: /daemonstate
      volumes:
        - name: host
          hostPath:
            path: /sys/fs/cgroup
        - name: state
          hostPath:
            path: /usr/local/daemonstate/
---
kind: Service
apiVersion: v1
metadata:
  name: ctlplane-daemonset
spec:
  selector:
    app: ctlplane-daemonset
  ports:
    - name: service
      port: 31000
      targetPort: 31000
    - name: monitor
      port: 8088
      targetPort: 8088
# TODO: Remove trailing spaces across whole project
