kind: Deployment
apiVersion: apps/v1
metadata:
  name: ctlplane-test-deployment123
spec:
  replicas: 4
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: web
          image: nginx:1.12
          resources:
            limits:
              memory: "500Mi"
              cpu: "1000m"
            requests:
              memory: "500Mi"
              cpu: "1000m"

