apiVersion: apps/v1
kind: Deployment
metadata:
  name: netshoot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-container
          image: nicolaka/netshoot
          env:
            - name: TESTT_PORT
              value: "$(TEST_PORT)"
          command: ["/bin/bash"]
          args: ["-c", "while true; do ping -c 1 localhost; sleep 60;done"]
          env:
            - name: SPECIAL
              valueFrom:
                configMapKeyRef:
                  name: special-config
                  key: SPECIAL_LEVEL	
          envFrom:
          - configMapRef:
              name: special-config
