apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: metric-exporter
    app.kubernetes.io/version: v0.0.1
  name: metric-exporter
  namespace: monitoring
spec:
  clusterIP: None
  ports:
  - name: habana-metrics
    port: 41611
  selector:
    app.kubernetes.io/name: metric-exporter-ds
