{
 "title": "Gaudi-HW",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "habanalabs_power_mW",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mwatt" } },
   "targets": [
    { "expr": "habanalabs_power_mW", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "habanalabs_memory_used_bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "habanalabs_memory_used_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "habanalabs_memory_free_bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "habanalabs_memory_free_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "habanalabs_temperature_onboard",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "habanalabs_temperature_onboard", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "habanalabs_device_config",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "habanalabs_device_config", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "habanalabs_kube_info",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expr": "habanalabs_kube_info", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "habanalabs_utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    { "expr": "habanalabs_utilization", "legendFormat": "__auto" }
   ]
  }
 ]
}