version: '3.8'
services:
  anythingllm:
    image: anything-llm
    container_name: anythingllm
    env_file:
      - .env
    ports:
    - "3001:3001"
    cap_add:
      - SYS_ADMIN
    user: "${UID:-1007}:${GID:-1007}"
    environment:
    # Adjust for your environment
      #- http_proxy=http://192.168.1.253:3128
      #- https_proxy=http://192.168.1.253:3128
      - STORAGE_DIR=/app/server/storage
      - JWT_SECRET="make this a large list of random numbers and letters 20+"
      - LLM_PROVIDER=ollama
      - OLLAMA_BASE_PATH=http://127.0.0.1:11434
      - OLLAMA_MODEL_PREF=llama2
      - OLLAMA_MODEL_TOKEN_LIMIT=4096
      - EMBEDDING_ENGINE=ollama
      - EMBEDDING_BASE_PATH=http://127.0.0.1:11434
      - EMBEDDING_MODEL_PREF=nomic-embed-text:latest
      - EMBEDDING_MODEL_MAX_CHUNK_LENGTH=8192
      - VECTOR_DB=lancedb
      - WHISPER_PROVIDER=local
      - TTS_PROVIDER=native
      - PASSWORDMINCHAR=8
      - AGENT_SERPER_DEV_KEY="SERPER DEV API KEY"
      - AGENT_SERPLY_API_KEY="Serply.io API KEY"
    volumes:
      - anythingllm_storage:/app/server/storage
      - /home/yulu/.anythingllm/.env:/app/server/.env
    restart: always

volumes:
  anythingllm_storage:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/yulu/.anythingllm
