apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tei-xeon-service.fullname" . }}-ervice-deploy
  labels:
  {{- include "tei-xeon-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.serviceDeploy.replicas }}
  selector:
    matchLabels:
      app: tei-reranking-service-deploy
    {{- include "tei-xeon-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: tei-reranking-service-deploy
      {{- include "tei-xeon-service.selectorLabels" . | nindent 8 }}
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
    spec:
      containers:
      - args: {{- toYaml .Values.serviceDeploy.teiRerankingServiceDeploy.args | nindent
          8 }}
        env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        - name: RERANK_MODEL_ID
          value: {{ .Values.global.qnaConfig.RERANK_MODEL_ID | quote }}
        image: {{ .Values.serviceDeploy.teiRerankingServiceDeploy.image.repository }}:{{
          .Values.serviceDeploy.teiRerankingServiceDeploy.image.tag | default .Chart.AppVersion
          }}
        name: tei-reranking-service-deploy
        ports:
        - containerPort: 80
        resources: {}
        volumeMounts:
        - mountPath: /data
          name: model-volume
        - mountPath: /dev/shm
          name: shm
      serviceAccountName: default
      volumes:
      - hostPath:
          path: /mnt/model
          type: Directory
        name: model-volume
      - emptyDir:
          medium: Memory
          sizeLimit: 1Gi
        name: shm