# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: router-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: router-service
  template:
    metadata:
      labels:
        app: router-service
    spec:
      #nodeName: satg-opea-4node-0
      nodeSelector:
        gmc: "chatqna"
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
               matchLabels:
                 app: router-service 
      serviceAccountName: default
      containers:
      - name: router-server
        #image: opea/gmcrouter:latest
        image: zhlsunshine/gmcrouter:stream
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: no_proxy
          value: {{.NoProxy}}
        - name: http_proxy
          value: {{.HttpProxy}}
        - name: https_proxy
          value: {{.HttpsProxy}}
        args:
        - "--graph-json"
        - {{.GRAPH_JSON}}
---
apiVersion: v1
kind: Service
metadata:
  name: router-service
spec:
  type: NodePort
  selector:
    app: router-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
