apiVersion: apps/v1
kind: Deployment
metadata:
  name: bmc-monitoring
  namespace: monitoring
  labels:
    app: bmc-monitoring
spec:
  selector:
    matchLabels:
      app: bmc-monitoring
  template:
    metadata:
      labels:
        app: bmc-monitoring
    spec:
      containers:
      - name: bmc-monitoring
        image: vault.habana.ai/habana-bmc-exporter/bmc-exporter
        imagePullPolicy: Always
        args:
          - "--config"
          - "/tmp/config.json"
        resources:
          limits:
            memory: 3Gi
            cpu: 500m
          requests:
            cpu: 350m
            memory: 2Gi
        # readiness probes mark the service available to accept traffic.
        readinessProbe:
          httpGet:
            path: /debug/readiness
            port: 5000
          initialDelaySeconds: 50
          periodSeconds: 15
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 2
        # liveness probes mark the service alive or dead (to be restarted).
        livenessProbe:
          httpGet:
            path: /debug/liveness
            port: 5000
          initialDelaySeconds: 50
          periodSeconds: 30
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 2
        volumeMounts:
        - name: config-volume
          mountPath: /tmp
        env:
          - name: USERNAME
            valueFrom:
              secretKeyRef:
                name: bmc-monitoring-secret
                key: username
          - name: PASSWORD
            valueFrom:
              secretKeyRef:
                name: bmc-monitoring-secret
                key: password
      volumes:
      - name: config-volume
        configMap:
          name: bmc-exporter-conf
