apiVersion: v1
kind: Service
metadata:
  name: bmc-monitoring-service
  namespace: monitoring
  labels:
    app: bmc-monitoring
spec:
  selector:
    app: bmc-monitoring
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      name: bmc-monitoring-endpoint
