apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tei.fullname" . }}-ervice-deploy
  labels:
  {{- include "tei.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.erviceDeploy.replicas }}
  selector:
    matchLabels:
      app: tei-embedding-service-deploy
    {{- include "tei.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: tei-embedding-service-deploy
      {{- include "tei.selectorLabels" . | nindent 8 }}
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
    spec:
      containers:
      - args: {{- toYaml .Values.erviceDeploy.teiEmbeddingServiceDeploy.args | nindent
          8 }}
        env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        envFrom:
        - configMapRef:
            name: qna-config
        image: {{ .Values.erviceDeploy.teiEmbeddingServiceDeploy.image.repository }}:{{
          .Values.erviceDeploy.teiEmbeddingServiceDeploy.image.tag | default .Chart.AppVersion
          }}
        name: tei-embedding-service-deploy
        ports:
        - containerPort: 80
        resources: {}
        volumeMounts:
        - mountPath: /data
          name: model-volume
        - mountPath: /dev/shm
          name: shm
      serviceAccountName: default
      volumes:
      - hostPath:
          path: /mnt/model
          type: Directory
        name: model-volume
      - emptyDir:
          medium: Memory
          sizeLimit: 1Gi
        name: shm