apiVersion: v1
kind: PersistentVolume
metadata:
  name: kong-postgres-pv
spec:
  capacity:
    storage: 8Gi        # Must match PVC request size
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/data     # Ensure this path exists on your worker node
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8s-master # Replace with actual node name

