deploy:
  chaqnaXeonBackendServerDeploy:
    image:
      repository: opea/gen-ai-comps
      tag: chatqna-megaservice-server
  replicas: 1
kubernetesClusterDomain: cluster.local
svc:
  ports:
  - name: service
    nodePort: 30888
    port: 8888
    targetPort: 8888
  type: NodePort
global:
  qnaConfig:
    REDIS_URL: "redis://chaqna-xeon-redis-vector-db.default.svc.cluster.local:6379"
    INDEX_NAME: "rag-redis"
    EMBEDDING_MODEL_ID: "BAAI/bge-base-en-v1.5"
    RERANK_MODEL_ID: "BAAI/bge-reranker-large"
    LLM_MODEL_ID: "Intel/neural-chat-7b-v3-3"
    TEI_EMBEDDING_ENDPOINT: "http://chaqna-xeon-tei-embedding-service-svc.default.svc.cluster.local:6006"
    TEI_RERANKING_ENDPOINT: "http://chaqna-xeon-tei-xeon-service-svc.default.svc.cluster.local:8808"
    TGI_LLM_ENDPOINT: "http://chaqna-xeon-tgi-service-svc.default.svc.cluster.local:9009"
    MEGA_SERVICE_HOST_IP: "172.16.3.15"
    HUGGINGFACEHUB_API_TOKEN: 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
    CHAT_BASE_URL: "${chat_qna_backendurl}/v1/chatqna"

    
    
    
    