deploy:
  chaqnaXeonBackendServerDeploy:
    image:
      repository: opea/gen-ai-comps
      tag: chatqna-megaservice-server
  replicas: 1
kubernetesClusterDomain: cluster.local
svc:
  ports:
  - name: service
    nodePort: 30888
    port: 8888
    targetPort: 8888
  type: NodePort
