apiVersion: apps/v1
kind: Deployment
metadata:
  name: ei-infer
spec:
  selector:
    matchLabels:
      app: ei-infer-pose-bf16-amx-app
  replicas: 1
  template:
    metadata:
      labels:
        app: ei-infer-pose-bf16-amx-app
    spec:
      containers:
      - name: ei-infer-pose-bf16-amx-app
        image: gar-registry.caas.intel.com/cpio/ei-inference-service-tensorflow:2022WW49
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "4Gi"
            cpu: "2"
          limits:
            memory: "4Gi"
            cpu: "2"
        env:
        - name: INFER_MODEL_NAME
          value: "ssd_mobilenet_bf16"
        - name: INPUT_QUEUE_HOST
          value: ei-redis-svc
        - name: OUTPUT_BROKER_HOST
          value: ei-redis-svc
        - name: INFER_TYPE
          value: pose-bf16-amx
        - name: ONEDNN_MAX_CPU_ISA
          value: AVX512_CORE_AMX
        - name: OMP_NUM_THREADS
          value: "1"
        ports:
        - name: web
          containerPort: 8000
      initContainers:
        - name: init-infer-pose-bf16-amx-app
          image: busybox:1.31
          command: ['sh', '-c', 'until nslookup ei-redis-svc; do echo waiting for ei-redis-svc; sleep 2; done;']
      nodeSelector:
        css-actor: demo