apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"ei-infer-pose-bf16-amx-deployment","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"ei-infer-pose-bf16-amx-app"}},"template":{"metadata":{"labels":{"app":"ei-infer-pose-bf16-amx-app"}},"spec":{"containers":[{"env":[{"name":"INFER_MODEL_NAME","value":"ssd_mobilenet_bf16"},{"name":"INPUT_QUEUE_HOST","value":"ei-redis-svc"},{"name":"OUTPUT_BROKER_HOST","value":"ei-redis-svc"},{"name":"INFER_TYPE","value":"pose-bf16-amx"},{"name":"ONEDNN_MAX_CPU_ISA","value":"AVX512_CORE_AMX"},{"name":"OMP_NUM_THREADS","value":"1"}],"image":"gar-registry.caas.intel.com/cpio/ei-inference-service-tensorflow:test","imagePullPolicy":"IfNotPresent","name":"ei-infer-pose-bf16-amx-app","ports":[{"containerPort":8000,"name":"web"}],"resources":{"limits":{"cpu":"1","memory":"2Gi"},"requests":{"cpu":"1","memory":"2Gi"}}}],"initContainers":[{"command":["sh","-c","until nslookup ei-redis-svc; do echo waiting for ei-redis-svc; sleep 2; done;"],"image":"busybox:1.31","name":"init-infer-pose-bf16-amx-app"}]}}}}
  creationTimestamp: "2023-03-17T02:38:14Z"
  generation: 10
  name: ei-infer-pose-bf16-amx-deployment
  namespace: default
  resourceVersion: "60128916"
  uid: 247d53ff-9ba2-429e-a3a9-72184a519f65
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ei-infer-pose-bf16-amx-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ei-infer-pose-bf16-amx-app
    spec:
      containers:
      - env:
        - name: INFER_MODEL_NAME
          value: ssd_mobilenet_bf16
        - name: INPUT_QUEUE_HOST
          value: ei-redis-svc
        - name: OUTPUT_BROKER_HOST
          value: ei-redis-svc
        - name: INFER_TYPE
          value: pose-bf16-amx
        - name: ONEDNN_MAX_CPU_ISA
          value: AVX512_CORE_AMX
        - name: OMP_NUM_THREADS
          value: "1"
        - name: TF_NUM_INTEROP_THREADS
          value: "1"
        - name: TF_NUM_INTRAOP_THREADS
          value: "4"
        image: gar-registry.caas.intel.com/cpio/ei-inference-service-tensorflow:2023WW11
        imagePullPolicy: IfNotPresent
        name: ei-infer-pose-bf16-amx-app
        ports:
        - containerPort: 8000
          name: web
          protocol: TCP
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: "1"
            memory: 2Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      initContainers:
      - command:
        - sh
        - -c
        - until nslookup ei-redis-svc; do echo waiting for ei-redis-svc; sleep 2;
          done;
        image: busybox:1.31
        imagePullPolicy: IfNotPresent
        name: init-infer-pose-bf16-amx-app
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-03-17T02:38:14Z"
    lastUpdateTime: "2023-03-21T07:28:19Z"
    message: ReplicaSet "ei-infer-pose-bf16-amx-deployment-67b9d5c694" has successfully
      progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2023-03-21T08:01:58Z"
    lastUpdateTime: "2023-03-21T08:01:58Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 10
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
