apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/name: tgi-gaudi-exporter
    app.kubernetes.io/version: v0.0.1
    release: prometheus-stack
  name: tgi-gaudi-exporter
  namespace: monitoring
spec:
  namespaceSelector:
      any: true
  selector:
    matchLabels:
      app: tgi-gaudi-service-deploy
  endpoints:
  - port: tgi-gaudi-svc
    interval: 30s
