apiVersion: apps/v1
kind: Deployment
metadata:
  name: ei-infer-try-2
spec:
  progressDeadlineSeconds: 86400
  selector:
    matchLabels:
      app: ei-infer-pose-multi-queue-app
  replicas: 1
  template:
    metadata:
      labels:
        app: ei-infer-pose-multi-queue-app
    spec:
      containers:
      - name: ei-infer-pose-multi-queue-app
        image: gar-registry.caas.intel.com/cpio/ei-inference-service-tensorflow:2023WW11
        imagePullPolicy: IfNotPresent
        resources:
        env:
        - name: INFER_MODEL_NAME
          value: "ssd_mobilenet_bf16"
        - name: INPUT_QUEUE_HOST
          value: ei-redis-svc
        - name: OUTPUT_BROKER_HOST
          value: ei-redis-svc
        - name: INFER_TYPE
          value: pose-bf16-amx
        - name: ONEDNN_MAX_CPU_ISA
          value: AVX512_CORE_AMX
        - name: OMP_NUM_THREADS
          value: "4"
        - name: TF_NUM_INTEROP_THREADS
          value: "1"   
        - name: TF_NUM_INTRAOP_THREADS
          value: "4" 
        
        
        ports:
        - name: web
          containerPort: 8000
      initContainers:
        - name: init-ei-infer-pose-multi-queue-app
          image: busybox:1.31
          command: ['sh', '-c', 'until nslookup ei-redis-svc; do echo waiting for ei-redis-svc; sleep 2; done;']
      nodeSelector:
        css-actor: demo